apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
    - name: nodeapp
      image: devopsmptech/myapp:2.0.12
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
